### ISSUE TITLE
Slow initial access to site using firefox on Linux Redhat 7

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/elvisproject#2]
The first time loading the elvisproject.ca page is very slow (it takes a few minutes). But once the page loads the first time it is just as fast as it is normally.

**Comment by ahankinson** [comment]
Sounds like it's still a firewall problem.

**Comment by crantila** [comment]
Yes, still the same firewall issue. As long as it only affects us, and only while we're in DDMAL, I'm not going to put too much effort into fixing it.
