### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvisproject#5]
The footer should have links to the SIMSSA project page, CIRMMT, Schulich School of Music, and McGill University. The copyright should go from 2013-2015.

**Comment by crantila** [comment]
Copyright notices should only list years in which the copyrighted item was modified, so it's correct as it is until something is changed, when it should be updated only on pages that are modified. I'm also pretty sure it's not okay to remove a copyright notice without consulting the copyright holders, though I doubt either of us mind in this case.

**Comment by musicus** [comment]
(I'm only concerned about the links, and the last updated date in the footer).

**Comment by musicus** [comment]
There is still no footer. The footer should look similar to the footer on http://database.elvisproject.ca.

**Comment by musicus** [comment]
Dates updated.
